application/backend/src/main/java/io/typerefinery/websight/models/components/Form.java
application/backend/src/main/java/io/typerefinery/websight/models/components/Inputtext.java
application/backend/src/main/resources/apps/typerefinery/components/content/button/template.html
application/backend/src/main/resources/apps/typerefinery/components/content/inputtext/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/inputtext/template.html
application/backend/src/main/resources/apps/typerefinery/components/structure/form/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/structure/form/form.html
application/backend/src/main/resources/apps/typerefinery/components/structure/form/script.js
application/backend/src/main/resources/apps/typerefinery/components/structure/page/body-end.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/head-libs.html
application/backend/src/main/resources/apps/typerefinery/web_root/main.css

Event Listeners for Form Components added.
On Submit the values are printed in the console in JSON Format.
Preview

form component updated. event listeners added.

---

application/backend/src/main/java/io/typerefinery/websight/models/components/Button.java
application/backend/src/main/resources/apps/typerefinery/components/content/button/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/button/template.html
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/components/structure/formpage/.content.xml

1. Rounded, Outlined, Raised and variants can now be added simultaneously.

button styling updated, few more styling added.

---

application/backend/src/main/java/io/typerefinery/websight/models/components/PieChart.java
application/backend/src/main/resources/apps/typerefinery/components/content/pieChart/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/pieChart/dataSource_1.json
application/backend/src/main/resources/apps/typerefinery/components/content/pieChart/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/pieChart/pieChart.html
application/backend/src/main/resources/apps/typerefinery/components/content/pieChart/script.js
application/backend/src/main/resources/apps/typerefinery/components/content/pieChart/template.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/head-libs.html
application/backend/src/main/resources/apps/typerefinery/web_root/main.css

Polar chart component created.

---

application/backend/src/main/resources/apps/typerefinery/components/structure/layouts/fourcols/.content.json
application/backend/src/main/resources/apps/typerefinery/components/structure/layouts/fourcols/template/.content.json
application/backend/src/main/resources/apps/typerefinery/components/structure/layouts/onecols/.content.json
application/backend/src/main/resources/apps/typerefinery/components/structure/layouts/onecols/template/.content.json
application/backend/src/main/resources/apps/typerefinery/components/structure/layouts/threecols/.content.json
application/backend/src/main/resources/apps/typerefinery/components/structure/layouts/threecols/template/.content.json

added layputs

---

application/backend/src/main/java/io/typerefinery/websight/models/components/SideBar.java
application/backend/src/main/resources/apps/typerefinery/components/content/sidebar/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/sidebar/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/sidebar/sidebar.css
application/backend/src/main/resources/apps/typerefinery/components/content/sidebar/sidebar.html
application/backend/src/main/resources/apps/typerefinery/components/content/sidebar/template.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/.content.json
application/backend/src/main/resources/apps/typerefinery/components/structure/page/body-end.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/head-libs.html

Please review and approve it .
**Sample sidebar tree**

Added sidebar component-tree

---

application/backend/src/main/resources/apps/typerefinery/components/content/barchart/dataSource_1.json
application/backend/src/main/resources/apps/typerefinery/components/content/barchart/script.js
application/backend/src/main/resources/apps/typerefinery/components/content/columnticker/columnstyle.css
application/backend/src/main/resources/apps/typerefinery/components/content/columnticker/columnticker.html
application/backend/src/main/resources/apps/typerefinery/components/content/header/template.html
application/backend/src/main/resources/apps/typerefinery/components/content/lineChart/dataSource_1.json
application/backend/src/main/resources/apps/typerefinery/components/content/lineChart/script.js
application/backend/src/main/resources/apps/typerefinery/components/content/pieChart/dataSource_1.json
application/backend/src/main/resources/apps/typerefinery/components/content/pieChart/script.js
application/backend/src/main/resources/apps/typerefinery/components/content/sidebar/sidebar.css
application/backend/src/main/resources/apps/typerefinery/components/content/ticker/script.js
application/backend/src/main/resources/apps/typerefinery/components/content/ticker/style.css
application/backend/src/main/resources/apps/typerefinery/components/structure/container/.content.json
application/backend/src/main/resources/apps/typerefinery/components/structure/layouts/dashboardcols/.content.json
application/backend/src/main/resources/apps/typerefinery/components/structure/layouts/dashboardcols/template/.content.json
application/backend/src/main/resources/apps/typerefinery/components/structure/page/body-end.html
application/backend/src/main/resources/apps/typerefinery/web_root/main.css
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/components/content/card/.content.xml

added css for dashboard

---

application/backend/src/main/resources/apps/typerefinery/components/content/map/map.html
application/backend/src/main/resources/apps/typerefinery/components/content/map/script.js

changes the map theme to bright .
component preview.

Map component

---

application/backend/src/main/java/io/typerefinery/websight/models/components/Button.java
application/backend/src/main/resources/apps/typerefinery/components/content/button/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/button/script.js
application/backend/src/main/resources/apps/typerefinery/components/content/button/template.html
application/backend/src/main/resources/apps/typerefinery/components/structure/form/script.js
application/backend/src/main/resources/apps/typerefinery/components/structure/page/head-libs.html

In this PR, I have the following things implemented:
1. Reset functionality for the form. (Resets all the input text to an empty value)
2. If the button has the type "button," then clicking on the button opens the redirection URL added in the dialogue box.

reset, button and submit functionality added for the button.

---

application/backend/src/main/java/io/typerefinery/websight/models/components/XAxisBarChart.java
application/backend/src/main/resources/apps/typerefinery/components/content/xAxisBarChart/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/xAxisBarChart/dataSource_1.json
application/backend/src/main/resources/apps/typerefinery/components/content/xAxisBarChart/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/xAxisBarChart/script.js
application/backend/src/main/resources/apps/typerefinery/components/content/xAxisBarChart/style.css
application/backend/src/main/resources/apps/typerefinery/components/content/xAxisBarChart/template.html
application/backend/src/main/resources/apps/typerefinery/components/content/xAxisBarChart/xAxisBarChart.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/head-libs.html

added x-axis bar chart

---

application/backend/src/main/java/io/typerefinery/websight/models/components/PieChartNonPolar.java
application/backend/src/main/resources/apps/typerefinery/components/content/pieChart/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/pieChartNonPolar/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/pieChartNonPolar/dataSource_1.json
application/backend/src/main/resources/apps/typerefinery/components/content/pieChartNonPolar/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/pieChartNonPolar/pieChartNonPolar.html
application/backend/src/main/resources/apps/typerefinery/components/content/pieChartNonPolar/script.js
application/backend/src/main/resources/apps/typerefinery/components/content/pieChartNonPolar/style.css
application/backend/src/main/resources/apps/typerefinery/components/content/pieChartNonPolar/template.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/head-libs.html

added pie chart non polar

---

application/backend/src/main/java/io/typerefinery/websight/models/components/RadioButton.java
application/backend/src/main/resources/apps/typerefinery/components/content/checkbox/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/checkbox/template.html
application/backend/src/main/resources/apps/typerefinery/components/content/radio/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/radio/template.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/body-end.html

Vue-model for the Radio button and checkbox components are implemented.
Everyone please do check this in your local machine.

v- model for checkbox and Radio button Implemented. 

---

application/backend/src/main/java/io/typerefinery/websight/models/components/D3Graph.java
application/backend/src/main/resources/apps/typerefinery/components/content/d3Graph/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/d3Graph/d3Graph.html
application/backend/src/main/resources/apps/typerefinery/components/content/d3Graph/dataSource_1.txt
application/backend/src/main/resources/apps/typerefinery/components/content/d3Graph/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/d3Graph/script.js
application/backend/src/main/resources/apps/typerefinery/components/content/d3Graph/template.html
application/backend/src/main/resources/apps/typerefinery/components/content/datatable/template.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/body-end.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/head-libs.html
application/backend/src/main/resources/apps/typerefinery/web_root/main.css

D3 Graph component added and data table headers are now controller from the vue instance

---

application/backend/src/main/resources/apps/typerefinery/components/content/datatable/template.html
application/backend/src/main/resources/apps/typerefinery/components/content/sidebar/template.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/body-end.html

Able to redirect one page to another page while selecting a tree node, but facing some issues.
1. Not able to get the selected node data from tree.
2. Not able to get the node label to check which node is get selected.

added code to redirect page

---

application/backend/src/main/resources/apps/typerefinery/components/content/datatable/template.html
application/backend/src/main/resources/apps/typerefinery/components/content/navbar/template.html
application/backend/src/main/resources/apps/typerefinery/components/content/sidebar/sidebar.css
application/backend/src/main/resources/apps/typerefinery/components/content/sidebar/template.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/body-end.html
application/backend/src/main/resources/apps/typerefinery/web_root/main.css
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/pages/feeds/.content.xml

Feeds page created

---

application/backend/src/main/resources/apps/typerefinery/components/content/inputtext/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/inputtext/template.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/body-end.html
application/backend/src/main/resources/apps/typerefinery/web_root/main.css
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/pages/search/.content.xml

1.added style in inputtext dialog 2. added search page.

---

tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/pages/search/.content.xml

Search page updated.

---

application/backend/src/main/resources/apps/typerefinery/components/content/columnticker/smallticker/script.js
application/backend/src/main/resources/apps/typerefinery/components/content/datatable/template.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/body-end.html

added code to redirect the pages

---

application/backend/src/main/resources/apps/typerefinery/components/content/columnticker/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/columnticker/columnstyle.css
application/backend/src/main/resources/apps/typerefinery/components/content/columnticker/smallticker/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/map/style.css
application/backend/src/main/resources/apps/typerefinery/components/content/pieChart/template.html
application/backend/src/main/resources/apps/typerefinery/components/content/radarChart/style.css
application/backend/src/main/resources/apps/typerefinery/components/structure/page/body-end.html
application/backend/src/main/resources/apps/typerefinery/web_root/main.css
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/pages/dashboard/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/pages/trends/.content.xml

please review and approve it.
Sample Output-

added dashboard

---

application/backend/src/main/java/io/typerefinery/websight/models/components/LineChartWithLabel.java
application/backend/src/main/resources/apps/typerefinery/components/content/lineChartWithLabel/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/lineChartWithLabel/dataSource_1.json
application/backend/src/main/resources/apps/typerefinery/components/content/lineChartWithLabel/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/lineChartWithLabel/lineChartWithLabel.html
application/backend/src/main/resources/apps/typerefinery/components/content/lineChartWithLabel/script.js
application/backend/src/main/resources/apps/typerefinery/components/content/lineChartWithLabel/template.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/head-libs.html
application/backend/src/main/resources/apps/typerefinery/web_root/main.css
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/pages/feeds/.content.xml

Added line Chart with Label
**Sample**

Added line chart with label

---

application/backend/src/main/java/io/typerefinery/websight/models/components/BreadCrumbs.java
application/backend/src/main/resources/apps/typerefinery/components/content/breadcrumbs/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/breadcrumbs/breadcrumbs.html
application/backend/src/main/resources/apps/typerefinery/components/content/breadcrumbs/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/content/breadcrumbs/template.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/body-end.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/head-libs.html
application/backend/src/main/resources/apps/typerefinery/web_root/main.css
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/pages/dashboard/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/pages/feeds/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/pages/search/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/pages/trends/.content.xml

Created Breadcrumbs components with dynamic contents in them.
Preview:

breadcrumb component added with dynamic content.

---

application/backend/src/main/resources/apps/typerefinery/components/structure/navbar/template.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/body-end.html
application/backend/src/main/resources/apps/typerefinery/web_root/main.css

please review and approve  it.
Sample output:-
Note: Its dynamic functionality is pending.

added menu items

---

application/backend/src/main/resources/apps/typerefinery/components/structure/header/script.js
application/backend/src/main/resources/apps/typerefinery/components/structure/header/template.html
application/backend/src/main/resources/apps/typerefinery/web_root/main.css

Sample output:-
Please review and approve.

added theme button

---

application/backend/src/main/java/io/typerefinery/websight/models/components/graphs/PieChart.java
application/backend/src/main/resources/apps/typerefinery/components/graphs/linechart/clientlibs/functions.js
application/backend/src/main/resources/apps/typerefinery/components/graphs/piechart/clientlibs/functions.js
application/backend/src/main/resources/apps/typerefinery/components/graphs/piechart/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/graphs/piechart/template.html
application/backend/src/main/resources/apps/typerefinery/components/graphs/xaxisbarchart/clientlibs/functions.js
application/backend/src/main/resources/apps/typerefinery/components/graphs/xaxisbarchart/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/web_root/dark.css
application/backend/src/main/resources/apps/typerefinery/web_root/light.css
application/backend/src/main/resources/apps/typerefinery/web_root/main.css

updated style for piechart

---

application/backend/src/main/resources/apps/typerefinery/components/graphs/linechart/clientlibs/functions.js
application/backend/src/main/resources/apps/typerefinery/components/graphs/piechart/clientlibs/functions.js

updated theme color.

---

application/backend/src/main/resources/apps/typerefinery/components/graphs/barchart/clientlibs/functions.js

updated theme for bar chart.

---

tests/end-to-end/cypress.config.ts
tests/end-to-end/support/const.ts
tests/end-to-end/tests/components/content/structure/component/forms/button/author.cy.ts
tests/end-to-end/tests/components/content/structure/component/forms/button/preview.cy.ts
tests/end-to-end/tests/components/content/structure/component/forms/checkbox/author.cy.ts
tests/end-to-end/tests/components/content/structure/component/forms/checkbox/preview.cy.ts
tests/end-to-end/tests/components/content/structure/component/forms/inputtext/author.cy.ts
tests/end-to-end/tests/components/content/structure/component/forms/inputtext/preview.cy.ts
tests/end-to-end/tests/components/content/structure/component/graphs/barchart/author.cy.ts
tests/end-to-end/tests/components/content/structure/component/graphs/barchart/preview.cy.ts
tests/end-to-end/tests/components/content/structure/component/graphs/linechart/author.cy.ts
tests/end-to-end/tests/components/content/structure/component/graphs/linechart/preview.cy.ts
tests/end-to-end/tests/components/content/structure/component/graphs/piechart/author.cy.ts
tests/end-to-end/tests/components/content/structure/component/graphs/piechart/preview.cy.ts
tests/end-to-end/tests/components/content/structure/component/widgets/table/author.cy.ts
tests/end-to-end/tests/components/content/structure/component/widgets/table/preview.cy.ts
tests/end-to-end/tests/components/content/structure/component/widgets/ticker/author.cy.ts
tests/end-to-end/tests/components/content/structure/component/widgets/ticker/preview.cy.ts
tests/end-to-end/tests/components/content/structure/pages/dashboard/author.cy.ts
tests/end-to-end/tests/components/content/structure/pages/dashboard/preview.cy.ts
tests/end-to-end/tests/components/content/structure/pages/feedpage/author.cy.ts
tests/end-to-end/tests/components/content/structure/pages/feedpage/preview.cy.ts
tests/end-to-end/tests/components/content/structure/pages/search/author.cy.ts
tests/end-to-end/tests/components/content/structure/pages/search/preview.cy.ts
tests/end-to-end/tests/components/content/structure/pages/trends/author.cy.ts
tests/end-to-end/tests/components/content/structure/pages/trends/preview.cy.ts

added test for components.

---

application/backend/src/main/resources/apps/typerefinery/components/structure/page/clientlibs/functions.js
application/backend/src/main/resources/apps/typerefinery/components/structure/page/head-start.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/theme/functions.js

In this PR,
1. I have added namespaces for the theme.

theme namespaces added.

---

tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/components/forms/checkbox/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/components/forms/radiobutton/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/components/forms/select/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/components/forms/textarea/.content.xml

added showcase for form component

---

tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/components/forms/.content.xml

A showcase preview is added below.

showcase page for form.

---

application/backend/src/main/resources/apps/typerefinery/components/widgets/table/clientlibs/functions.js
application/backend/src/main/resources/apps/typerefinery/components/widgets/table/clientlibs/style.css

Added search input field.
Added pagination and sorting.

updated table funtionality.

---

application/backend/src/main/resources/apps/typerefinery/components/layout/header/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/widgets/table/clientlibs/functions.js
application/backend/src/main/resources/apps/typerefinery/components/widgets/table/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/widgets/table/mock/datasource1.json
application/backend/src/main/resources/apps/typerefinery/components/widgets/table/mock/datasource2.json
application/backend/src/main/resources/apps/typerefinery/components/widgets/table/table.html
application/backend/src/main/resources/apps/typerefinery/components/widgets/table/variant.html
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/components/forms/button/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/components/forms/checkbox/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/components/forms/input/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/content/simpleheader/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/pages/form/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/pages/report/.content.xml

Reports Page preview:-
Form page preview

Added showcases pages

---

tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/pages/dashboard/.content.xml

added dashboard page.

---

application/backend/src/main/java/io/typerefinery/websight/models/components/widgets/Table.java
application/backend/src/main/resources/apps/typerefinery/components/widgets/table/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/widgets/table/template/.content.json
application/backend/src/main/resources/apps/typerefinery/components/widgets/table/templates/flowsample.json
application/backend/src/main/resources/apps/typerefinery/components/widgets/table/templates/table.json

enabled flow in table component.

---

application/backend/src/main/java/io/typerefinery/websight/models/components/widgets/Chart.java
application/backend/src/main/resources/apps/typerefinery/components/widgets/chart/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/widgets/chart/template/.content.json
application/backend/src/main/resources/apps/typerefinery/components/widgets/chart/templates/chart.json
application/backend/src/main/resources/apps/typerefinery/components/widgets/chart/templates/flowsample.json

enable flow for chart component.

---

application/backend/src/main/java/ai/typerefinery/websight/models/components/BaseComponent.java
application/backend/src/main/java/ai/typerefinery/websight/models/components/layout/Container.java
application/backend/src/main/resources/apps/typerefinery/components/dialog/tabs/margin/.content.json
application/backend/src/main/resources/apps/typerefinery/components/dialog/tabs/padding/.content.json
application/backend/src/main/resources/apps/typerefinery/components/dialog/tabs/style/.content.json
application/backend/src/main/resources/apps/typerefinery/components/layout/container/dialog/.content.json

Margin and padding style added to container only, now its used for all components.
Please Review and approve it.

added margin and padding style to all component

---

application/backend/src/main/java/ai/typerefinery/websight/models/components/widgets/Editor.java
application/backend/src/main/resources/apps/typerefinery/components/forms/fields/checkbox/variant.html
application/backend/src/main/resources/apps/typerefinery/components/forms/fields/input/variant.html
application/backend/src/main/resources/apps/typerefinery/components/forms/fields/radio/variant.html
application/backend/src/main/resources/apps/typerefinery/components/forms/fields/select/clientlibs/functions.js
application/backend/src/main/resources/apps/typerefinery/components/forms/fields/select/variant.html
application/backend/src/main/resources/apps/typerefinery/components/forms/form/clientlibs/functions.js
application/backend/src/main/resources/apps/typerefinery/components/forms/input/clientlibs/behaviour.js
application/backend/src/main/resources/apps/typerefinery/components/structure/page/clientlibs-header/functions.js
application/backend/src/main/resources/apps/typerefinery/components/widgets/editor/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/widgets/editor/editor.html
application/backend/src/main/resources/apps/typerefinery/components/widgets/editor/variant.html
application/frontend/src/static/clientlibs/vendor/select/style.css

In this PR,
I have tested the read and write operations in forms and fixed the bugs that were encountered.
Along with that, now the editor component (CODE_MIRROR) and select component can take up values from the endpoint.

Read and Write In forms

---

tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/forms/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/forms/connection/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/forms/project/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/forms/query/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/forms/theme/.content.xml

added required forms in CMS

---

application/backend/src/main/java/ai/typerefinery/websight/models/components/layout/Container.java
application/backend/src/main/resources/apps/typerefinery/components/dialog/tabs/alignment/.content.json
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/content/footer/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/content/header/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/pages/dashboard/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/pages/form/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/pages/report/.content.xml

refactor dashboard page and change styling for containers

---

application/backend/src/main/resources/apps/typerefinery/components/widgets/table/README.md
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/components/widgets/table/.content.xml

[README.md](https://github.com/typerefinery-ai/typerefinery-websight/pull/252/files?short_path=e7bea24#diff-e7bea24e2f9b701c27a9c754a27d108125b40a120489d1dc3a14f164c0901394)

Added table Doc.

---

application/backend/src/main/resources/apps/typerefinery/components/widgets/map/clientlibs/functions.js
application/backend/src/main/resources/apps/typerefinery/components/widgets/map/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/widgets/map/map.html
application/backend/src/main/resources/apps/typerefinery/components/widgets/map/templates/flowsample.json
application/frontend/src/static/clientlibs/vendor/map/leafletmap/leaflet.css

update for tms connected and update url for image

---

application/backend/src/main/java/ai/typerefinery/websight/models/components/layout/Container.java
application/backend/src/main/resources/apps/typerefinery/components/dialog/tabs/containerchild/.content.json
application/backend/src/main/resources/apps/typerefinery/components/dialog/tabs/containertitle/.content.json
application/backend/src/main/resources/apps/typerefinery/components/layout/container/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/layout/container/variant.sectionwithtitle.html
application/backend/src/main/resources/apps/typerefinery/components/structure/page/clientlibs-header/style.css

added style for container having title

---

application/backend/src/main/resources/apps/typerefinery/components/forms/fields/button/variant.hamburger.html
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/content/header-with-hamburger/.content.xml

added header with hamburger showcase-page.

---

application/backend/src/main/java/ai/typerefinery/websight/models/components/forms/Select.java
application/backend/src/main/resources/apps/typerefinery/components/forms/fields/select/clientlibs/functions.js
application/backend/src/main/resources/apps/typerefinery/components/forms/fields/select/dialog/.content.json

This PR includes the following changes:
1. After fetching from the endpoint mentioned, the user can select the id and value for the select dropdown.

Fetching Options via JSON/Get Modified for Select Dropdown

---

application/backend/src/main/java/ai/typerefinery/websight/models/components/forms/Button.java
application/backend/src/main/resources/apps/typerefinery/components/clientlibs/clientlibs-header/.content.json
application/backend/src/main/resources/apps/typerefinery/components/clientlibs/clientlibs-header/hidebuttonelement.js
application/backend/src/main/resources/apps/typerefinery/components/clientlibs/clientlibs-header/togglecomponent.js
application/backend/src/main/resources/apps/typerefinery/components/content/text/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/forms/fields/button/clientlibs/functions.js
application/backend/src/main/resources/apps/typerefinery/components/forms/fields/button/dialog/.content.json

Initially the text element is hidden.
When toggle the button the text element get visible.

added new action type to button to toggle visibility of a target

---

application/backend/src/main/java/ai/typerefinery/websight/jobs/flow/FlowJobConsumer.java
application/backend/src/main/java/ai/typerefinery/websight/models/components/widgets/Chart.java
application/backend/src/main/java/ai/typerefinery/websight/services/flow/FlowService.java
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/components/editor/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/components/widgets/chart/.content.xml
tests/content/src/main/content/jcr_root/content/typerefinery-showcase/pages/components/widgets/ticker/.content.xml

Now we are able to enable flow api and able to get flow data.

Bug/ flow enable not work for components

---

application/backend/src/main/java/ai/typerefinery/websight/models/components/layout/NavigationItemComponent.java
application/backend/src/main/resources/apps/typerefinery/components/clientlibs/clientlibs-header/dropdown.js
application/backend/src/main/resources/apps/typerefinery/components/clientlibs/clientlibs-header/modal.js
application/backend/src/main/resources/apps/typerefinery/components/content/text/clientlibs/functions.js
application/backend/src/main/resources/apps/typerefinery/components/content/title/clientlibs/functions.js
application/backend/src/main/resources/apps/typerefinery/components/forms/fields/button/clientlibs/functions.js
application/backend/src/main/resources/apps/typerefinery/components/forms/fields/button/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/widgets/table/clientlibs/functions.js
application/backend/src/main/resources/apps/typerefinery/components/widgets/table/dialog/.content.json
application/backend/src/main/resources/apps/typerefinery/components/widgets/table/templates/os-triage-caseid-tags.json
application/backend/src/main/resources/apps/typerefinery/components/widgets/table/variant.html

This PR Includes,
Bubbles up the modal from Iframe to Parent

Bubbling Modal from Iframe to Parent
